version: '3.5'
services:
  app:
    # Nginx conf file must have proxy as build name, app in this case
    build: app
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask_network
    volumes:
      - sessions:/app/flask_session/
      - nginx:/etc/nginx/
    depends_on:
      - db
    env_file:
      - env-vars.txt

  nginx:
    build: nginx
    restart: always
    ports:
      - 8080:80
      - 4343:443
    networks:
      - flask_network
    env_file:
      - env-vars.txt
    volumes:
      - nginx:/etc/nginx/

  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env-vars.txt
    

networks:
  flask_network:
    enable_ipv6: false

volumes:
  postgres_data:
  sessions:
  nginx: